### ISSUE TITLE
Usage of `oc adm inspect`

### ISSUE THREAD

**Issue by sferich888** [openshift-knative/must-gather#2]
Can the [following lines](https://github.com/openshift-knative/must-gather/blob/master/bin/gather_knative#L68-L78) be improved, thought the use of `oc adm inspect`?

Would this simplify the collection process?

**Comment by nak3** [comment]
`oc adm inspect` does not collect `oc logs` like https://github.com/openshift-knative/must-gather/blob/main/bin/gather_knative#L75, does it? If it does not contain `oc logs`, I prefer to the current script.

**Comment by nak3** [comment]
Correction for my above comment. `oc adm inspect` will collect the pod logs if we include the namespaces. So I think it is worth the use `oc adm inspect`

**Comment by sferich888** [comment]
Is someone on the knative team going to update the collection?

**Comment by sferich888** [comment]
@nak3 any updates?

**Comment by nak3** [comment]
/assign

Sorry for the delay. I will hand over this or work on it by myself.
